apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: icici-cacerts-job
  namespace: icici-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: icici-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: icici
      component_name: icici-net
      namespace: icici-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://34.229.91.35:8200
      authpath: localicici-net-auth
      secretcryptoprefix: secretsv2/data/crypto/peerOrganizations/icici-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/icici-net/ca/icici
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=CH/ST=Zurich/L=Zurich/O=Icici/CN=ca.icici-net.bank.com
