apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-bank-com-ca
  namespace: supplychain-bank-com
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-bank-com-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: supplychain-bank-com
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplychain-admin
        
    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://35.175.171.11:8200
      authpath: localsupplychain-bank-com-auth
      secretcert: secretsv2/data/crypto/ordererOrganizations/supplychain-bank-com/ca?ca.supplychain-bank-com-cert.pem
      secretkey: secretsv2/data/crypto/ordererOrganizations/supplychain-bank-com/ca?supplychain-bank-com-CA.key
      secretadminpass: secretsv2/data/credentials/supplychain-bank-com/ca/supplychain?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: orderer
      external_url_suffix: supplychain-bank-com.bank.com
