apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-cacerts-job
  namespace: supplychain-bank-com
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: supplychain
      component_name: supplychain-bank-com
      namespace: supplychain-bank-com    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://35.175.171.11:8200
      authpath: localsupplychain-bank-com-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-bank-com/ca
      secretcredentialsprefix: secretsv2/data/credentials/supplychain-bank-com/ca/supplychain
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.supplychain-bank-com.bank.com
